### ISSUE TITLE
Resizing a windows doesn't work

### ISSUE THREAD

**Issue by GustavoJCL** [chase/awrit#38] opened 2024-04-03 02:02 UTC
Hi, when i tried to resize my kitty windows it just show a dark bar instead of resizing the page
![image](https://github.com/chase/awrit/assets/93671143/e2dc5509-48f7-40c7-b3f6-61a09133a7db)

**Comment by chase** [comment] 2024-04-03 08:39
Thanks for reporting.

Please make one issue per problem/feature request in the future. I've split the video support problem into another issue.

**Comment by chase** [comment] 2024-04-08 05:39
This is actually a duplicate of https://github.com/chase/awrit/issues/8

**Closed** 2024-04-08 05:40 UTC
Labels: bug, duplicate
